web/Controllers/OdkupController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.Rendering;
using Microsoft.EntityFrameworkCore;
using web.Data;
using web.Models;
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Identity;

namespace web.Controllers
{
    [Authorize]
    public class OdkupController : Controller
    {
        
        private readonly TrtaContext _context;
        private readonly UserManager<ApplicationUser> _usermanager;

        public OdkupController(TrtaContext context, UserManager<ApplicationUser> userManager)
        {
            _context = context;
            _usermanager = userManager;
        }

        // GET: Odkup
        public async Task<IActionResult> Index(string sortOrder, string searchString, string currentFilter, int? pageNumber)
        {
            ViewData["CurrentSort"] = sortOrder;
            ViewData["PridelekId"] = String.IsNullOrEmpty(sortOrder) ? "pridelekId_desc" : "";
            ViewData["Kolicina"] = sortOrder == "kolicina"  ? "kolicina_desc" : "kolicina";
            ViewData["CenaNaKg"] = sortOrder == "cena" ? "cena_desc" : "cena";
            ViewData["Leto"] = sortOrder == "leto" ? "leto_desc" : "leto";

            if (searchString != null)
            {
                pageNumber = 1;
            }
            else
            {
                searchString = currentFilter;
            }

            ViewData["CurrentFilter"] = searchString;
            
            var odkup = from v in _context.Odkup
                select v;
            
            if (!String.IsNullOrEmpty(searchString))
            {
                odkup = odkup.Where(s => s.PridelekId.ToString().Contains(searchString)
                                    || s.Kolicina.ToString().Contains(searchString)
                                    || s.CenaNaKg.ToString().Contains(searchString)
                                    || s.letoMeritve.ToString().Contains(searchString));
            }
            
            switch (sortOrder)
            {
                case "pridelekId_desc":
                    odkup = odkup.OrderByDescending(v => v.PridelekId);
                    break;
                case "kolicina_desc":
                    odkup = odkup.OrderByDescending(v => v.Kolicina);
                    break;
                case "kolicina":
                    odkup = odkup.OrderBy(v => v.Kolicina);
                    break;
                case "cena_desc":
                    odkup = odkup.OrderByDescending(v => v.CenaNaKg);
                    break;
                case "cena":
                    odkup = odkup.OrderBy(v => v.CenaNaKg);
                    break;
                case "leto_desc":
                    odkup = odkup.OrderByDescending(v => v.letoMeritve);
                    break;
                case "leto":
                    odkup = odkup.OrderBy(v => v.letoMeritve);
                    break;
                default:
                    odkup = odkup.OrderBy(v => v.PridelekId);
                    break;
            }
            int pageSize = 5;
            return View(await PaginatedList<Odkup>.CreateAsync(odkup.AsNoTracking(), pageNumber ?? 1, pageSize));
        }

        // GET: Odkup/Details/5
        public async Task<IActionResult> Details(int? id)
        {
            if (id == null || _context.Odkup == null)
            {
                return NotFound();
            }

            var odkup = await _context.Odkup
                .FirstOrDefaultAsync(m => m.OdkupId == id);
            if (odkup == null)
            {
                return NotFound();
            }

            return View(odkup);
        }

        // GET: Odkup/Create
        [Authorize(Roles = "Administrator")]
        public IActionResult Create()
        {
            return View();
        }

        // POST: Odkup/Create
        // To protect from overposting attacks, enable the specific properties you want to bind to.
        // For more details, see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Create([Bind("OdkupId,PridelekId,Kolicina,CenaNaKg,letoMeritve")] Odkup odkup)
        {
            var currentUser = await _usermanager.GetUserAsync(User);
            if (ModelState.IsValid)
            {
                odkup.DateCreated = DateTime.Now;
                odkup.DateEdited = DateTime.Now;
                odkup.Owner= currentUser;
                _context.Add(odkup);
                await _context.SaveChangesAsync();
                return RedirectToAction(nameof(Index));
            }
            return View(odkup);
        }

        // GET: Odkup/Edit/5
        [Authorize(Roles = "Administrator")]
        public async Task<IActionResult> Edit(int? id)
        {
            if (id == null || _context.Odkup == null)
            {
                return NotFound();
            }

            var odkup = await _context.Odkup.FindAsync(id);
            if (odkup == null)
            {
                return NotFound();
            }
            return View(odkup);
        }

        // POST: Odkup/Edit/5
        // To protect from overposting attacks, enable the specific properties you want to bind to.
        // For more details, see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Edit(int id, [Bind("OdkupId,PridelekId,Kolicina,CenaNaKg,letoMeritve")] Odkup odkup)
        {
            if (id != odkup.OdkupId)
            {
                return NotFound();
            }

            if (ModelState.IsValid)
            {
                try
                {
                    _context.Update(odkup);
                    await _context.SaveChangesAsync();
                }
                catch (DbUpdateConcurrencyException)
                {
                    if (!OdkupExists(odkup.OdkupId))
                    {
                        return NotFound();
                    }
                    else
                    {
                        throw;
                    }
                }
                return RedirectToAction(nameof(Index));
            }
            return View(odkup);
        }

        // GET: Odkup/Delete/5
        [Authorize(Roles = "Administrator")]
        public async Task<IActionResult> Delete(int? id)
        {
            if (id == null || _context.Odkup == null)
            {
                return NotFound();
            }

            var odkup = await _context.Odkup
                .FirstOrDefaultAsync(m => m.OdkupId == id);
            if (odkup == null)
            {
                return NotFound();
            }

            return View(odkup);
        }

        // POST: Odkup/Delete/5
        [HttpPost, ActionName("Delete")]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> DeleteConfirmed(int id)
        {
            if (_context.Odkup == null)
            {
                return Problem("Entity set 'TrtaContext.Odkup'  is null.");
            }
            var odkup = await _context.Odkup.FindAsync(id);
            if (odkup != null)
            {
                _context.Odkup.Remove(odkup);
            }
            
            await _context.SaveChangesAsync();
            return RedirectToAction(nameof(Index));
        }

        private bool OdkupExists(int id)
        {
          return _context.Odkup.Any(e => e.OdkupId == id);
        }
    }
}

web/Controllers/TrteController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.Rendering;
using Microsoft.EntityFrameworkCore;
using web.Data;
using web.Models;
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Identity;

namespace web.Controllers
{
    [Authorize]
    public class TrteController : Controller
    {
        private readonly TrtaContext _context;
        private readonly UserManager<ApplicationUser> _usermanager;

        public TrteController(TrtaContext context, UserManager<ApplicationUser> userManager)
        {
            _context = context;
            _usermanager = userManager;
        }

        // GET: Trte
        public async Task<IActionResult> Index()
        {
              return View(await _context.Trte.ToListAsync());
        }

        // GET: Trte/Details/5
        public async Task<IActionResult> Details(int? id)
        {
            if (id == null || _context.Trte == null)
            {
                return NotFound();
            }

            var trte = await _context.Trte
            .Include(s => s.Vinogradi)
                .ThenInclude(e => e.Pridelek)
            .AsNoTracking()
            .FirstOrDefaultAsync(m => m.TrteId == id);
            if (trte == null)
            {
                return NotFound();
            }

            return View(trte);
        }

        // GET: Trte/Create
        [Authorize(Roles = "Administrator")]
        public IActionResult Create()
        {
            return View();
        }

        // POST: Trte/Create
        // To protect from overposting attacks, enable the specific properties you want to bind to.
        // For more details, see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Create([Bind("TrteId,Sorta")] Trte trte)
        {
            var currentUser = await _usermanager.GetUserAsync(User);
            if (ModelState.IsValid)
            {
                trte.DateCreated = DateTime.Now;
                trte.DateEdited = DateTime.Now;
                trte.Owner= currentUser;
                _context.Add(trte);
                await _context.SaveChangesAsync();
                return RedirectToAction(nameof(Index));
            }
            return View(trte);
        }

        // GET: Trte/Edit/5
        [Authorize(Roles = "Administrator")]
        public async Task<IActionResult> Edit(int? id)
        {
            if (id == null || _context.Trte == null)
            {
                return NotFound();
            }

            var trte = await _context.Trte.FindAsync(id);
            if (trte == null)
            {
                return NotFound();
            }
            return View(trte);
        }

        // POST: Trte/Edit/5
        // To protect from overposting attacks, enable the specific properties you want to bind to.
        // For more details, see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Edit(int id, [Bind("TrteId,Sorta")] Trte trte)
        {
            if (id != trte.TrteId)
            {
                return NotFound();
            }

            if (ModelState.IsValid)
            {
                try
                {
                    _context.Update(trte);
                    await _context.SaveChangesAsync();
                }
                catch (DbUpdateConcurrencyException)
                {
                    if (!TrteExists(trte.TrteId))
                    {
                        return NotFound();
                    }
                    else
                    {
                        throw;
                    }
                }
                return RedirectToAction(nameof(Index));
            }
            return View(trte);
        }

        // GET: Trte/Delete/5
        [Authorize(Roles = "Administrator")]
        public async Task<IActionResult> Delete(int? id)
        {
            if (id == null || _context.Trte == null)
            {
                return NotFound();
            }

            var trte = await _context.Trte
                .FirstOrDefaultAsync(m => m.TrteId == id);
            if (trte == null)
            {
                return NotFound();
            }

            return View(trte);
        }

        // POST: Trte/Delete/5
        [HttpPost, ActionName("Delete")]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> DeleteConfirmed(int id)
        {
            if (_context.Trte == null)
            {
                return Problem("Entity set 'TrtaContext.Trte'  is null.");
            }
            var trte = await _context.Trte.FindAsync(id);
            if (trte != null)
            {
                _context.Trte.Remove(trte);
            }
            
            await _context.SaveChangesAsync();
            return RedirectToAction(nameof(Index));
        }

        private bool TrteExists(int id)
        {
          return _context.Trte.Any(e => e.TrteId == id);
        }
    }
}

web/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>@ViewData["Title"] - Slovenska Trta</title>
    <link rel="stylesheet" href="~/lib/bootstrap/dist/css/bootstrap.min.css" />
    <link rel="stylesheet" href="~/css/site.css" asp-append-version="true" />
    <link rel="stylesheet" href="~/web.styles.css" asp-append-version="true" />
    <link rel="stylesheet" href="~/css/stil.css" asp-append-version="true" />
</head>
<body>
    <header>
        <nav class="navbar navbar-expand-sm box-shadow mb-3 barjansa">
            <div class="container-fluid barjansa1">
                <a class="navbar-brand barjansa1" asp-area="" asp-controller="Home" asp-action="Index">
                    <img src="~/Slike/SlovenskaTrtaLogo.png" class= "slika" title="title" alt="additional title"/>
                </a>
                <button class="navbar-toggler barjansa" type="button" data-bs-toggle="collapse" data-bs-target=".navbar-collapse" aria-controls="navbarSupportedContent"
                        aria-expanded="false" aria-label="Toggle navigation">
                    <span class="navbar-toggler-icon"></span>
                </button>
                <div class="navbar-collapse collapse d-sm-inline-flex flex-sm-row-reverse barjansa1">
                    <partial name="_LoginPartial"/>
                    <ul class="navbar-nav flex-grow-1 velikost">
                        <li class="nav-item gumb">
                            <a class="nav-link nav-item gumbTekst" asp-area="" asp-controller="Home" asp-action="Index">Domov</a>
                        </li>
                        <li class="nav-item gumb">
                            <a class="nav-link gumbTekst" asp-area="" asp-controller="Home" asp-action="Privacy">Zasebnost</a>
                        </li>
                        <li class="nav-item gumb">
                            <a class="nav-link gumbTekst" asp-area="" asp-controller="Trte" asp-action="Index">Trte</a>
                        </li>
                        <li class="nav-item gumb">
                            <a class="nav-link gumbTekst" asp-area="" asp-controller="Vinogradi" asp-action="Index">Vinogradi</a>
                        </li>
                        <li class="nav-item gumb">
                            <a class="nav-link gumbTekst" asp-area="" asp-controller="Pridelek" asp-action="Index">Pridelek</a>
                        </li>
                        <li class="nav-item gumb">
                            <a class="nav-link gumbTekst" asp-area="" asp-controller="Odkup" asp-action="Index">Odkup</a>
                        </li>
                    </ul>
                </div>
            </div>
        </nav>
    </header>
    <div class="container">
        <main role="main" class="pb-3">
            @RenderBody()
        </main>
    </div>
    <img src = "~/Slike/TrteVSloveniji.jpg" class = "ozadje"/>

    <footer class="border-top footer text-muted">
        <div class="container">
            &copy; 2022 - Slovenska trta - <a asp-area="" asp-controller="Home" asp-action="Privacy">Zasebnost</a>
        </div>
    </footer>
    <script src="~/lib/jquery/dist/jquery.min.js"></script>
    <script src="~/lib/bootstrap/dist/js/bootstrap.bundle.min.js"></script>
    <script src="~/js/site.js" asp-append-version="true"></script>
    @await RenderSectionAsync("Scripts", required: false)
</body>
</html>